services:
  db:
    image: postgres:9.4
    container_name: db
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
      - POSTGRES_DB=postgres
    ports:
      - "5432:5432"
    volumes:
      - "psql-data:/var/lib/postgresql/data"
    networks:
      - psql-network

  redis:
    image: redis:5.0-alpine3.10
    container_name: redis
    ports:
      - "6379:6379"
    networks:
      - redis-network

  vote:
    build: ./vote
    container_name: vote-service-container
    restart: always
    depends_on:
      - redis
    ports:
      - "8080:80"
    networks:
      - redis-network

  result:
    build: ./result
    container_name: result-service-container
    depends_on:
      - db
    ports:
      - "4000:4000"
    networks:
      - psql-network
  
  worker:
    build: ./worker
    container_name: worker-service-container
    depends_on:
      - db
      - redis
    networks:
      - redis-network
      - psql-network

volumes:
  psql-data:

networks:
  redis-network:
  psql-network:
